// Define the type of the environment variables.
declare interface Env {
  readonly NODE_ENV: string;
  readonly NG_APP_API_URL: string;
  readonly NG_APP_TITLE: string;
  [key: string]: any;
}

// // Choose how to access the environment variables.
// // Remove the unused options.
//
// // 1. Use import.meta.env.YOUR_ENV_VAR in your code. (conventional)
declare interface ImportMeta {
  readonly env: Env;
}
//
// // 2. Use _NGX_ENV_.YOUR_ENV_VAR in your code. (customizable)
// // You can modify the name of the variable in angular.json.
// // ngxEnv: {
// //  define: '_NGX_ENV_',
// // }
// declare const _NGX_ENV_: Env;
//
// // 3. Use process.env.YOUR_ENV_VAR in your code. (deprecated)
// declare namespace NodeJS {
//   export interface ProcessEnv extends Env {}
// }


// Typed application environment variables.
// The base `Env` interface + `import.meta.env` typing live in `src/env.d.ts`
// (generated by @ngx-env/builder). This declaration merges into `Env` to add
// autocomplete/type-checking for this project's own `NG_APP_*` variables.
